name: "spot_inferno_full_dance"
slices_per_minute: 516
moves {
  type: "sway"
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 4
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 8
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 12
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 16
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 20
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 24
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
      value: 0.08
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 28
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
      value: -0.08
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 32
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 36
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 40
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 44
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 48
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 52
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 56
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: -0.05
    }
    roll {
      value: -0.15
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 60
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: 0.05
    }
    roll {
      value: 0.15
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 64
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 68
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 72
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 76
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 80
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 84
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 88
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: -0.15
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 92
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: 0.15
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 96
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 100
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.09
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 104
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 108
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 112
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.11
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 116
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.11
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 120
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 124
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "unstow"
  start_slice: 108
  requested_slices: 8
}
moves {
  type: "workspace_arm_move"
  start_slice: 116
  requested_slices: 14
  workspace_arm_move_params {
    rotation {
      roll {
        value: 0.05
      }
      pitch {
        value: 0.05
      }
      yaw {
        value: 0.05
      }
    }
    translation {
      x {
      }
      y {
      }
      z {
        value: 0.12
      }
    }
    absolute {
    }
    frame: ARM_MOVE_FRAME_CENTER_OF_FOOTPRINT
    easing: EASING_CUBIC_IN_OUT
    dance_frame_id {
    }
  }
}
moves {
  type: "chicken_head"
  start_slice: 130
  requested_slices: 144
  chicken_head_params {
    bob_magnitude {
      x {
        value: 0.02
      }
      y {
        value: 0.02
      }
      z {
        value: 0.01
      }
    }
    beats_per_cycle {
      value: 1
    }
    follow {
    }
  }
}
moves {
  type: "sway"
  start_slice: 120
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: 0.05
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 124
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.05
    }
    horizontal {
      value: 0.05
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 128
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 132
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 136
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 140
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 144
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 148
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 152
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 156
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 160
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 164
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 168
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 172
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 176
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 180
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.07
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 184
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 188
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 192
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 196
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: -0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 200
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 204
  requested_slices: 4
  sway_params {
    vertical {
    }
    horizontal {
      value: 0.2
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 208
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 212
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 216
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 220
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.1
    }
    horizontal {
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 224
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: -0.12
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 228
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: 0.12
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 232
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: -0.12
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 236
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: 0.12
    }
    roll {
    }
    pivot: PIVOT_FRONT
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 240
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: -0.14
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 244
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.14
    }
    horizontal {
      value: 0.14
    }
    roll {
    }
    pivot: PIVOT_CENTER
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 248
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.17
    }
    horizontal {
      value: -0.14
    }
    roll {
    }
    pivot: PIVOT_HIND
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
moves {
  type: "sway"
  start_slice: 252
  requested_slices: 4
  sway_params {
    vertical {
      value: 0.2
    }
    horizontal {
      value: 0.14
    }
    roll {
    }
    pivot: PIVOT_HIND
    style: SWAY_STYLE_STANDARD
    pronounced {
      value: 0.5
    }
    hold_zero_axes {
    }
  }
}
