name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
    contents: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint spot_choreo_utils packages
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
        - { python: "3.10" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.python }}

      - name: Lint sources
        uses: pre-commit/action@v3.0.1
